config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  root 'food_items#index'

  resources :food_items, :users, :orders, :order_products, :carts, :orders, :order_receipts

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :order_products

  def add_food_item(food_item_id)
    order_product = order_products.where(food_item_id: food_item_id).first
    if order_product
      order_product.quantity += 1
    else
      order_product = order_products.build(food_item_id: food_item_id)
      order_product.quantity = 1
    end
    order_product
  end
end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  acts_as_taggable
  has_many :order_products
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_one :order_receipt
  has_many :order_products, dependent: :destroy

  def add_order_products_from_cart(cart)
    total_amount = 0
    cart.order_products.each do |order_product|
      order_product.cart = nil
      self.order_products << order_product
      total_amount = total_amount + order_product.amount
    end
    self.amount = total_amount
  end
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
  belongs_to :cart
  belongs_to :order
  belongs_to :food_item

  before_save :save_amount

  def save_amount
    self.amount = quantity * food_item.price
  end
end

app/models/order_receipt.rb
class OrderReceipt < ActiveRecord::Base
  belongs_to :order
  before_save :calculate_total_amount

  def calculate_total_amount
    self.service_charge = order.amount * 0.15
    self.total_amount = order.amount + service_charge
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart

  before_action :set_cart
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:search]
      @food_items = FoodItem.tagged_with(params[:search].gsub(' ', ','), parse: true, any: true)
    else
      @food_items = FoodItem.all
    end
  end
end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def create
    @order_product = @cart.add_food_item(params[:food_item_id])

    if @order_product.save
      redirect_to :root, notice: "Added item successfully."
    else
      redirect_to :root
    end
  end

  def destroy
    order_product = OrderProduct.find(params[:id])
    if order_product.quantity <= 1
      order_product.destroy
    else
      order_product.quantity -= 1
    end

    if order_product.save
      if @cart.order_products.empty?
        redirect_to :root, notice: "Item deleted successfully"
      else
        redirect_to cart_path(@cart), notice: "Item deleted successfully"
      end
    else
      redirect_to :root, notice: "Can not be Deleted"
    end
  end
end

app/controllers/order_receipts_controller.rb
class OrderReceiptsController < ApplicationController
  def show
    @order_receipt = OrderReceipt.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def create
    order = Order.new
    order.add_order_products_from_cart(@cart)
    order.user = current_user
    if order.save
      @cart.destroy
      session[:cart_id] = nil
      OrderReceipt.create(order_id: order.id)
      redirect_to :root, notice: "Order Created Successfully."
    else
      redirect_to :root, notice: "Please recreate the Order."
    end
  end

  def index
    @orders = Order.where(user_id: current_user.id)
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<table>
  <tr>
    <th> Product Name </th>
    <th> Product Description </th>
    <th> Product Price </th>
    <th> Product Quantity </th>
  </tr>

  <% @cart.order_products.each do |order_product| %>
    <tr>
      <td>
        <%= order_product.food_item.name %>
      </td>
      <td>
        <%= order_product.food_item.description %>
      </td>
      <td>
        <%= order_product.food_item.price %>
      </td>
      <td>
        <%= order_product.quantity %>
      </td>
      <td>
        <%= button_to "Delete", order_product_path(order_product.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button' %>
      </td>
    </tr>
  <% end %>
</table>
<div class='list_action'>
  <%= button_to 'Checkout', orders_path(cart_id: @cart.id), class: 'button' %></br>
</div>

app/views/food_items/index.html.erb
<%= form_tag(food_items_path, :method => 'get', id: "search-form") do %>
<%= text_field_tag :search, nil, placeholder: "Search Tags" %>
<%= button_tag "Search" %>
<% end %>

<table>
  <tr>
    <th> Product Name </th>
    <th> Product Description </th>
    <th> Product Price </th>
  </tr>
  <% @food_items.each do |food_item| %>
    <tr>
      <td>
        <%= food_item.name %>
      </td>
      <td>
        <%= food_item.description %>
      </td>
      <td>
        <%= food_item.price %>
      </td>
      <td class='list_actions'>
        <%= button_to 'Add To Cart', order_products_path(food_item_id: food_item), class: 'button' %></br>
      </td>
    </tr>
  <% end %>
</table>

app/views/headers/_menu_header.html.erb
<div id = "header">
  <div id="menu_header" class="top-bar">
    <div class="top-bar-right">
      <ul class="menu">
        <li> <%= link_to "Home", root_path %> </li>
        <% if current_user %>
          <% if session[:cart_id] %>
            <li> <div id="cart"> <%= link_to "Cart", cart_path(session[:cart_id])%> </div> </li>
          <% end %>
          <li> <div id="my_orders"> <%= link_to "My Orders", orders_path %> </div> </li>
          <li> <div id="display_email" class="links"> <%= current_user.email %> </div> </li>
          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %> </li>
        <% elsif current_user.nil? %>
          <li> <div id="login" class="links"> <%= link_to "Sign In", new_user_session_path %> </div> </li>
          <li> <div id="login" class="links"> <%= link_to "Sign Up", new_user_registration_path %> </div> </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="notice"> <%= notice %> </div>
<br/>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'headers/menu_header' %>

    <%= yield %>

  </body>
</html>

app/views/order_receipts/show.html.erb
<table>
  <tr>
    <th> Order ID </th>
    <th> Order Amount </th>
    <th> Service Charge </th>
    <th> Total Amount </th>
  </tr>
  <tr>
    <td>
      <%= @order_receipt.order.id %>
    </td>
    <td>
      <%= @order_receipt.order.amount %>
    </td>
    <td>
      <%= @order_receipt.try(:service_charge) %>
    </td>
    <td>
      <%= @order_receipt.total_amount %>
    </td>
  </tr>
  <tr>
    <th> Total </th>
    <td> </td>
    <td> </td>
    <th> <%= @order_receipt.total_amount %> </th>
  </tr>
</table>

app/views/orders/index.html.erb
<% if @orders.present? %>
  <table>
    <tr>
      <th> Order ID </th>
      <th> Amount </th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td>
          <%= order.id %>
        </td>
        <td>
          <%= order.amount %>
        </td>
        <td class='list_actions'>
          <div style="display: flex">
            <%= button_to 'View', order_path(id: order.id), method: :get, class: 'button', id: "view_order" %></br>
            <%= button_to 'View Receipt', order_receipt_path(id: order.order_receipt.id), method: :get, class: 'button' %></br>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
   There are no orders.
<% end %>

app/views/orders/show.html.erb
<h3> Order Number <%= @order.id %>
<table>
  <tr>
    <th> Product Name </th>
    <th> Product Price </th>
    <th> Product Quantity </th>
    <th> Amount </th>
  </tr>
  <% @order.order_products.each do |op| %>
    <tr>
      <td>
        <%= op.food_item.name %>
      </td>
      <td>
        <%= op.food_item.price %>
      </td>
      <td>
        <%= op.quantity %>
      </td>
      <td>
        <%= op.amount %>
      </td>
    </tr>
  <% end %>
  <tr>
    <th> Total </th>
    <td> </td>
    <td> </td>
    <th colspan="3"> <%= @order.amount %> </th>
  </tr>
</table>